Change the way price list rows are added.
This fixes the following error raised by Django 1.9:

  ValueError: <SubmittedPriceListRow: Submitted price list row>
  instance isn't saved. Use bulk=False or save the object first.